- .pre-commit-config.yaml
- app/create_app.py
Locally this causes problems as we don't have HTTPS and remotely it is unnecessary as PaaS enforces HTTPS
> BAU: Set force HTTPS to false on Talisman config

- app/config.py
- app/create_app.py
- app/default/routes.py
- app/filters.py
- app/models/application_summary.py
- app/templates/dashboard.html
- requirements.txt
- tests/api_data/endpoint_data.json
- tests/test_application_summary.py
Add dashboard which reads from the application store to get existing applications and POSTs to application store to create new applications 
Note: This reads account ID from a path param which should be replaced once we can read it from the session. Also this assumes there will always be at least one application created, as it relies on params of the existing application to derive the fund and round of the new one (let me know if there's a better way to derive this
> FS-877: add landing page

- .github/workflows/govcloud.yml
Previously the chromedriver version was fixed in the tests whilst the version of chrome was the latest, this created a mismatch where the test would no longer run: 
e.g.
```
E       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
E       Current browser version is 102.0.5005.61 with binary path /usr/bin/google-chrome
```
this fixes by unfixing the version of chromedriver used by github actions so it always downloads the latest version.
> BAU: Fix tests (unfix chromedriver version)

- .github/workflows/govcloud.yml
Same change as https://github.com/communitiesuk/funding-design-service-workflows/pull/6
We need to apply this separately as this repo has forked the shared deployment workflow.
> BAU: limit test deploys to main branch

- .github/workflows/xforms_builder.yml
Action was breaking after merge of https://github.com/communitiesuk/funding-service-design-frontend/pull/53
This fixes the action and makes the intended change of allowing the build to work if the branch name contains upper-case characters (which need to be lowecased to make a valid docker tag)
> BAU: fix xforms action

- manifest.yml
Previously, deployment of our fork was failing as it was missing the S3 binding e.g.
```
2022-08-01T17:11:53.31+0100 [APP/PROC/WEB/0] ERR /usr/src/app/runner/dist/server/services/uploadService.js:22
2022-08-01T17:11:53.31+0100 [APP/PROC/WEB/0] ERR const s3Credentials = vcapJson["aws-s3-bucket"][0].credentials;
2022-08-01T17:11:53.31+0100 [APP/PROC/WEB/0] ERR ^
2022-08-01T17:11:53.31+0100 [APP/PROC/WEB/0] ERR TypeError: Cannot read property '0' of undefined
```
This should fix that error by binding the apps to the bucket
> FS-1263: bind form runner to s3

- .github/workflows/govcloud.yml
The end-to-end tests which rely on hitting the form-runner host are failing due to DNS issues.
Temporarily use a .cloudapps.digital domain whilst these are resolved.
> BAU: temporarily use cloudapps domain for tests

- .github/workflows/govcloud.yml
The tests which use the form runner JSON are currently failing as we are not running our fork. Ignore these temporarily so we can un-block unrelated frontend changes from being merged.
> BAU: ignore application tests whilst form runner is unavailable

- .github/workflows/govcloud.yml
- app/models/helpers.py
- manifest-dev.yml
- manifest-test.yml
On the new custom domain the form POST was failing as it was missing the credentials to communicate on the server-side, this uses the existing `FORMS_SERVICE_PRIVATE_HOST` config to provide the correct host.
Also adds better exception handling, as previous nothing was logged when this failed as the function returned `None`.
> FS-1163 add forms private host

- manifest-dev.yml
- manifest-test.yml
Rendering the task list was failing on the deployed environments as the `FUND_STORE_API_HOST` was not configured, e.g.
```
2022-08-15T09:48:36.03+0100 [APP/PROC/WEB/0] OUT {"name": "app.create_app", "levelname": "INFO", "message": "Fetching data from 'http://fund_store/funds/funding-service-design'.", "funcName": "get_data", "pathname": "/home/vcap/app/app/default/data.py", "lineno": 26, "instance_index": "0", "logType": "application"}
```
> BAU: add missing config for fund store API host

- manifest-dev.yml
- manifest-test.yml
This was causing 404s from the Start Now button
> BAU: remove trailing slash from authenticator URLs in config

- config/envs/default.py
Without these set we can throw an exception when going to the dashboard e.g.
> BAU: add missing default round ID and fund ID to config

- app/models/application_summary.py
- tests/test_application_summary.py
Displays timestamps in London time rather than UTC.
> FS-1544: localise timezone

- manifest-form-runner.yml
Add SINGLE_REDIS=true env var to form runner manifest to enable single instance redis bindings on the form runner
> FS-1638 Add redis support

- app/templates/tasklist.html
Previously we were erroneously applying a filter on the already human readable fund name, which turned it to lower-case
> BAU: fix fund casing

- app/templates/dashboard.html
- app/templates/index.html
- app/templates/partials/available_in_language.html
Extracted a macro for language availability component, add to dashboard & landing page.
Relevant prototypes:
https://fsd-funding-prototype-v2.herokuapp.com/s22-application/applicant-dashboard
https://fsd-funding-prototype-v2.herokuapp.com/s20-application/invite-page
Images:
https://user-images.githubusercontent.com/117724519/202692956-d0878580-5f09-4c03-933b-15ebbf8987f0.png
https://user-images.githubusercontent.com/117724519/202693022-7316718f-a7ab-4154-841c-24b75b969a86.png
> FS-1757: Add language availability notice

- .github/workflows/tag-to-release.yaml
Use shared workflow for tagging, instead of copy-pasting between repos.
Nature of github actions makes this very tricky to test on a branch, so plan is to merge this in, test and then revert of fix-forward.
> FS-2172: use shared workflow for tag

- form_jsons/public/cy/cyllid-sydd-ei-angen.json
- form_jsons/public/cy/gwybodaeth-am-y-sefydliad.json
- form_jsons/public/cy/gwybodaeth-am-yr-ased.json
- form_jsons/public/en/asset-information.json
- form_jsons/public/en/funding-required.json
- form_jsons/public/en/organisation-information.json
A recent push to the form runner has made the workaround for making the hints look like labels redundant
https://github.com/communitiesuk/digital-form-builder/commit/92f715a8e5aba6bb5c6433f66a892667dcc5ac3a
> Updating forms, styles not needed

- app/templates/404.html
- app/templates/500.html
- app/templates/accessibility_statement.html
- app/templates/application_submitted.html
- app/templates/base.html
- app/templates/cof_r2w2_all_questions.html
- app/templates/contact_us.html
- app/templates/cookie_policy.html
- app/templates/dashboard.html
- app/templates/index.html
- app/templates/tasklist.html
- requirements-dev.in
- requirements-dev.txt
- tests/test_routes.py
As highlighted in the accessibility audit, pages should have unique titles, previously most pages just used the `service_title`
This adds a `pageHeading` variable in the base template which is used in the <title> tag if set and as the `h1` to avoid duplication and encourage re-use of this pattern in future.
> FS-2190: unique title tags

- form_jsons/public/cy/gwybodaeth-am-y-sefydliad.json
- form_jsons/public/en/organisation-information.json
On pages 30-34 of the accessibility audit report - a few specific instances are mentioned where there were many inputs that were relevant to one another, but were not grouped appropriately in a fieldset, this caused confusion for screen readers as they weren't informed of the relation between the inputs automatically, and had to snoop around to get an understanding of the grouping and relation.
This change encloses related optional fields in a `<fieldset>`, and changes any enclosed hints to corresponding a `<label>`, meaning screen readers will detect the grouping and relation of the inputs automatically, and announce the correct label/information for the user.
Note that this has been change for both English/Welsh forms.
> FS-2194: Group form controls

- form_jsons/public/en/applicant-information.json
- form_jsons/public/en/asset-information.json
- form_jsons/public/en/community-benefits.json
- form_jsons/public/en/community-engagement.json
- form_jsons/public/en/community-representation.json
- form_jsons/public/en/community-use.json
- form_jsons/public/en/declarations.json
- form_jsons/public/en/environmental-sustainability.json
- form_jsons/public/en/feasibility.json
- form_jsons/public/en/funding-required.json
- form_jsons/public/en/inclusiveness-and-integration.json
- form_jsons/public/en/local-support.json
- form_jsons/public/en/organisation-information.json
- form_jsons/public/en/project-costs.json
- form_jsons/public/en/project-information.json
- form_jsons/public/en/project-qualification.json
- form_jsons/public/en/risk.json
- form_jsons/public/en/skills-and-resources.json
- form_jsons/public/en/upload-business-plan.json
- form_jsons/public/en/value-to-the-community.json
Accessibility Report (Pages 15-16) states there are page titles (h2's) which are duplicated within forms. 
This ticket addresses this by making h2 titles unique within each form.
Jira ticket: https://digital.dclg.gov.uk/jira/secure/RapidBoard.jspa?rapidView=110&projectKey=FS&view=detail&selectedIssue=FS-2235#:~:text=Funding%20Service%20Design-,FS%2D2235,-Close%20detail%20(%20T
> Fs 2235 fix duplicated page headings

- app/default/application_routes.py
- app/default/content_routes.py
- app/default/data.py
- app/templates/cof_r2_all_questions.html
- app/templates/tasklist.html
- tests/api_data/endpoint_data.json
- tests/test_all_questions.py
Uses endpoint added in https://github.com/communitiesuk/funding-service-design-fund-store/pull/50
Updates:
- Change of URL to get to page showing all questions (now /all_questions/<fund_short_name>/<round_short_name> eg. `/all_questions/cof/r2w2`
- Redirect added so old url works (`/cof_r2w2_all_questions`)
- Goes along with changes to the fund store to be able to retrieve by short_name, and with the authenticator so it dynamically generates the link to the all questions page
> BAU: All questions round 2 window 3 page

- .github/workflows/build-deploy-forms.yml
Added env var for assessment as it was causing the e2e assessment test to fail when the workflow was running via application frontend.
https://github.com/communitiesuk/funding-service-design-frontend/actions/runs/4182482703/jobs/7245810232
> BAU: Pass in Assessment frontend URL env var for e2e assessment

- .github/workflows/govcloud.yml
Related to https://github.com/communitiesuk/funding-service-design-frontend/pull/270/files. I forgot to add it to govcloud.yml
Added environment var for the Assessment url, so that the assessment e2e test doesn't fail to run in the pipeline.
N/A
N/A
> BAU - Add env var for Assessment e2e test

- .github/workflows/build-deploy-forms.yml
- .github/workflows/govcloud.yml
Disabling e2e tests on Dev as it's giving false positives. This is mainly due to the environment being constantly deployed which disrupts the e2e test run.
N/A
N/A
> BAU - Disable e2e tests running against Dev env.

- .github/workflows/build-deploy-forms.yml
- form_jsons/public/cy/buddion-cymunedol.json
- form_jsons/public/cy/cefnogaeth-leol.json
- form_jsons/public/cy/costau'r-prosiect.json
- form_jsons/public/cy/cyllid-sydd-ei-angen.json
- form_jsons/public/cy/cymhwystra'r-prosiect.json
- form_jsons/public/cy/cynaliadwyedd-amgylcheddol.json
- form_jsons/public/cy/cynhwysiant-ac-integreiddio.json
- form_jsons/public/cy/cynrychiolaeth-gymunedol.json
- form_jsons/public/cy/datganiadau.json
- form_jsons/public/cy/defnydd-cymunedol.json
- form_jsons/public/cy/dichonoldeb.json
- form_jsons/public/cy/gwerth-i'r-gymuned.json
- form_jsons/public/cy/gwybodaeth-am-y-prosiect.json
- form_jsons/public/cy/gwybodaeth-am-y-sefydliad.json
- form_jsons/public/cy/gwybodaeth-am-yr-ased.json
- form_jsons/public/cy/gwybodaeth-am-yr-ymgeisydd.json
- form_jsons/public/cy/lanlwythwch-y-cynllun-busnes.json
- form_jsons/public/cy/risg.json
- form_jsons/public/cy/sgiliau-ac-adnoddau.json
- form_jsons/public/cy/ymgysylltu-a'r-gymuned.json
Change description
A brief description of the pull request
Removing duplicated page titles in form runner form configuration, this issue was raised in the DAC Accessibility Report (Pages 15-16).
[V ] Unit tests and other appropriate tests added or updated
[V] README and other documentation has been updated / added (if needed)
[V] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
This can be tested by ensuring the correct title displays in e2e (pick up h2s) and exploratory testing whilst navigating through the journey.
Screenshots of UI changes (if applicable)
> Fs 2308 duplicated cof form h2s welsh

- .github/workflows/tag-to-release.yaml
Change description
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
[ - ] Unit tests and other appropriate tests added or updated
[ - ] README and other documentation has been updated / added (if needed)
[ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
> tagging action permissions update

- manifest-dev.yml
- manifest-test.yml
Jira ticket:
https://digital.dclg.gov.uk/jira/browse/FS-2422
Added health-check-invocation-timeout: 10 to the manifest file to increase the Cloud foundry runs healthchecks timeout limit (currently at 1 second) to 10 seconds on Dev and Test env. As having it at 1 second sometimes disrupted the e2e tests running against Dev and Test due to the running app restarting because of the healthchecks.
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#health-check-invocation-timeout
https://cli.cloudfoundry.org/en-US/v6/v3-set-health-check.html
Run the e2e tests locally pointing to Dev as the manifest change for Dev env has been deployed already. 
N/A
> FS-2422: Add health check invocation timeout for Application (frontend) microservice

- app/create_app.py
- app/default/routes.py
- app/models/fund.py
- tests/test_routes.py
- tests/test_start_page.py
Hotfix
We are seeing errors in Sentry (eg. https://funding-service-design-team-dl.sentry.io/issues/4061658169/) following release of the new routes in frontend to support eg. frontend.dev.gids.dev/cof redirecting to /cof/r2w3. The requests for /favicon.ico are generating lots of noise in the logs as we don't have a fund called 'favicon.ico'.
This change tackles this in the following ways:
- Adds a `before_request` filter to return a simple 404 when someone asks for /favicon.ico (not the full 404 page as that also tries to retrieve fund details)
- Checks for all requests to /something_else whether something_else is a valid fund short code.
Navigate to the following URLs when running the docker-runner locally:
- http://localhost:3008/cof/r2w3 - should return 200
- http://localhost:3008/cof/ …
> hotfix - filter out favicon requests and check for valid fund short code

- app/default/content_routes.py
- app/default/data.py
- app/models/round.py
- app/templates/footer.html
- requirements-dev.txt
- requirements.txt
- tests/api_data/endpoint_data.json
- tests/test_data.py
- tests/test_start_page.py
###FS-2429 Make privacy notice url dynamic in footer
Previously, frontend footer links for Privacy notice was hardcoded url, this now has changed to retrieve the url from the fund data endpoint and redirects when visiting /privacy url. It also has a fallback of a hardcoded privacy notice url when failing to retrieve from endpoint.
> Privacy Notice link in footer is dynamic and has fallback

- app/create_app.py
- app/default/account_routes.py
- app/default/content_routes.py
- app/default/data.py
- app/models/round.py
- app/templates/contact_us.html
- app/templates/dashboard_single_fund.html
- app/templates/header.html
- app/templates/partials/applications_table.html
- tests/api_data/endpoint_data.json
- tests/test_data.py
- tests/test_start_page.py
Feedback URL is now dynamic - loaded from the round data. If it's not present in the round, or the round is not supplied, redirects to contact us.
Removed function to determine default fund and round as we no longer need this now we are multi fund - instead of falling back to a default we return a 404 which displays default contact details.
Navigate to the main page for different funds - the feedback link in the header should contain the fund and round short codes as querystring params.
Relies on latest night shelter branch for fund-store as this contains the db field for the feedback url.
> Fs 2827 dynamic feedback link

- app/templates/partials/tasklist_section.html
Remove index printing in favour of configured section names in the fund store
Supports new project-name-ns section, see: https://github.com/communitiesuk/funding-service-design-fund-store/pull/85
> BAU: Removed visual index print

- app/filters.py
https://digital.dclg.gov.uk/jira/browse/FS-2916
Fix, a flask_babel filter is rebasing the time by default and therefore removing the BST time from the datetime object (and showing application last edited times as an hour behind actual), this has been changed so that it does not happen by default.
> implement fix to prevent flask_babel rebasing the datetime object

- app/create_app.py
- tests/conftest.py
- tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2978
Improvement on this [PR ]( https://github.com/communitiesuk/funding-service-design-frontend/pull/357)work
Use default round contact details in contact us page when provided round_short_name is incorrect
> Fs 2978 contact page if fund id is correct but round id is incorrect 2

- app/templates/header.html
FS-3348 removing feedback link from text in beta banner
Navigate to the frontend and view the beta banner
> Remove feedback text from beta banner

- app/templates/end_of_application_feedback_page_1.html
- app/templates/end_of_application_feedback_page_2.html
- app/templates/end_of_application_feedback_page_3.html
- app/templates/end_of_application_feedback_page_4.html
- app/templates/feedback_generic_survey.html
Remove calls to render hidden fields for specific data items as the existing call to `form.hidden_tag()` already does this. Thereby removed duplicate fields.
Navigate to feedback form and use dev tools to view the hidden fields - as per screenshot below. No visible UI chagnes to users
> FS-3387 - Removing duplicate fields

- app/templates/end_of_application_feedback_page_4.html
Minor change to change a `div` to a `label` and fix a critical accessibility bug
Launch feedback survey, navigate to page 4 and check that the text for the hours spent field is a label element
> fs-3432 added label element

- .pre-commit-config.yaml
- copilot/environments/addons/funding-service-magic-links.yml
- manifest-dev.yml
- manifest-test.yml
https://dluhcdigital.atlassian.net/browse/FS-3441
- Added pre-commit 'Yelp/detect-secrets' to prevent committing of secrets to code base
- Ignore false positives by marking them with `pragma: allowlist secret`
- disabled the plugins `HexHighEntropyString` & `Base64HighEntropyString` which tend to detect lot of false positives
- Add a secret/API key/password to any of the file type
For eg. `API_KEY= "125fdfbdjhbj5989"`
- stage the file & commit it.
- Notice the commit is failed with errors.
> FS-3441 added yelp hook for secrets

- app/default/application_routes.py
- app/helpers.py
- app/models/round.py
- config/envs/development.py
- tests/conftest.py
- tests/test_data.py
Adding support for 'mark this section as complete' at the end of each section - updated function that creates the form reghydration payload for the form-runner to pass in whether or not this round uses the 'mark as complete' functionality.
Goes with the following PRs:
https://github.com/communitiesuk/digital-form-builder/pull/309
https://github.com/communitiesuk/funding-service-design-application-store/pull/228
https://github.com/communitiesuk/funding-service-design-fund-store/pull/125
Update a round to have `markAsCompleteEnabled=true`
Start an application in that round
Complete a section and you should see the 'mark this section as complete' radio fields on the summary …
> Fs 3356 mark as complete

- config/envs/test.py
* Private key is no longer passed via environment, so causes an error on deploy
* However, private key is not even needed in this service
+ref: BAU-3317
+semver: minor
> Remove Unneeded Private Key definition

- .github/workflows/copilot_deploy.yml
References to notification in the manifest replacement section should have been frontend
> Replaced notification with frontend

- app/templates/all_questions/en/cyp_r1_all_questions_en.html
Fixed the all questions script under https://github.com/communitiesuk/funding-service-design-fund-store/pull/173 and then re-ran to generate the CYP all questions page with the missing word counts
> fs-3704 rerun all questions script to include max words

- app/filters.py
Fixed the time displayed on the applications page to fit the govuk guidelines by making it use a 12 hour time format. Also fixing the am/pm being incorrect when showing noon or midnight
When opening the last edited page the following should be true
- Last edited value should in the 12 hour clock format
- If an application was last edited at 12 last edited should display the correct suffix
> FS-3577 Fixed last edited time displaying noon as midnight

- .github/workflows/copilot_deploy.yml
* dependabot does not have access to github secrets
* We don't want to run builds without access to secrets
* Add in a rule to ignore dependabot deploys
+ref: BAU
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
> BAU Fixing dependabot errors for copilot deploys

- static/src/js/fsd_cookies.js
- Start setting domain with cookie so it persists across access-funding
- If access-funding then we take `access-funding.levellingup.gov.uk`
- If test env we take `test.gids.dev`, local environment is `localhost`
> BAU: Fixing cookie domain based on prod/test/local env

- app/default/account_routes.py
- app/default/data.py
- app/helpers.py
- tests/conftest.py
- tests/test_dashboard.py
- tests/test_lru_cache.py
- tests/test_start_page.py
When switching between welsh and english on the dashboard, the fund title was not always translating correctly. This was due to the caching on retrieval of fund data - the cache wasn't invalidated by the change of language.
Updated the fund retrieval method to take in the language and increased the cache size to 2, meaning that when changing languages we always get the right value. Also checked other fund retrieval methods to make them respect language choice with the caching, and updated unit tests to mock the `get_lang()` function as needed.
Navigate to the dashboard
Switch between welsh and english - observe the fund title being correctly translated
> Fs 3964 fix fund title

- app/default/account_routes.py
- app/templates/dashboard_all.html
- tests/conftest.py
- tests/test_dashboard.py
- tests/test_tasklist.py
- tests/utils.py
If you are in welsh, and move from the all applications view to a specific fund dashboard, and that fund does not support welsh, forces the language cookie to welsh.
Also added some missing unit tests for existing functionality, as well as testing this fix.
- Navigate to a fund that supports welsh
- Change to welsh
- Navigate to 'view all my applications'
- Navigate to a fund that does not support welsh
- The dashboard for that fund should force you into english - all text should display in english and the cookie should change to `en`
> fs-2942 dashboard forces language if welsh not avaialble, added tests

- app/default/account_routes.py
- app/default/routes.py
- tests/test_dashboard.py
Updated `build_application_Data_for_display` to filter applications to only the visible round if `round_short_name` is displayed. eg:
- `frontend/account?fund=COF&round=R3W3` will only display applications from R3W3
- `frontend/account?fund=COF` will still display any applications from all rounds in that fund
> fs-4144 updating rules on which applications to display

- app/default/application_routes.py
- app/default/routes.py
- app/models/round.py
- app/templates/fund_start_page.html
- app/templates/tasklist.html
- tests/api_data/test_data.py
- Start consuming new `is_expression_of_interest` property instead of checking the short name
---
> FS-4232: Add "is_expression_of_interest" as a proper round property

- app/templates/tasklist.html
Fixed the logic around showing deadline date if the tasklist is for Expression of Interest
Create or view an application that is marked for EOI and check that the Deadline date isn't shown on the tasklist page
> FS-4321: Fix deadline appearing in EOI tasklist

- app/templates/partials/round_closed_warning.html
COF have confirmed they do not want us to email any incomplete EOI applications when the round closes tonight. We need to amend the 'window closed' banner text as at the moment it says we will email these.
> Fs 4430 remove email msg

- copilot/fsd-frontend/manifest.yml
FS-4411: Overprovision instance
##Change description
Reduce the number of instance to 1 in Dev and change the ECS launch_type to Fargate-spot.
Unit tests and other appropriate tests added or updated
README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
_Will check after deployment by logging into the ECS console and view the service and instance configuration
Screenshots of UI changes (if applicable)
> FS-4411:Over-provision instance and change to Fargate-spot

- app/templates/partials/applications_table.html
There is wide inconsistency with date format across the application form.
Manually tested
> FS-4506:date-format-comply-with-GDS-v1

- app/templates/dashboard_single_fund.html
- app/templates/partials/start-application-button.html
When there are 2 rounds open in the same fund, the automated tests just use the first ‘start a new application’ button they find. If we add an id to the button that includes the fund/round short names we can select based on which round we are targeting.
Manually Tested
> FS-3888:add-id-to-start-new-application-v1

- app/create_app.py
- app/default/application_routes.py
- app/filters.py
- app/helpers.py
- app/templates/partials/applications_table.html
- app/templates/partials/tasklist_section.html
- app/templates/tasklist.html
- tests/test_tasklist.py
This change allows the `/tasklist` route to load for funds that have
been closed and applications that have been otherwise submitted.
Additionally we check to see if those conditions are true and pass a new
flag `is_read_only_summary` to the form runner which will present that
tasklist sections summary screen without the option to modify your
answers.
This should allow applicants to see answers they've previously submitted
for complete submissions as well as for rounds in the past.
Functionality depends on https://github.com/communitiesuk/digital-form-builder/pull/551
New view/ continue application behaviour:
An application that has already been submitted now shown with “View application”
> FS-3664 View submitted applications and applications for previous rounds

- app/templates/header.html
- static/src/styles/tasklist.css
https://dluhcdigital.atlassian.net/browse/FS-4546
- Replaced anchor tag with a form button having csrf token
- Button styled as link to be consistent with design
- Login to frontend and verify /sessions/sign-out are logging user out as expected
Application signout:
> Fs 4546 post signout

- app/default/application_routes.py
- app/default/data.py
- app/helpers.py
- app/templates/fund-round-notification.html
- app/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/test_fund_round_notification.py
Adding round close notification page and relevant validations before directing the page to the user.
https://dluhcdigital.atlassian.net/browse/FS-4666
When user is in the middle of a application filling process & have a round close same time will show this page
> Adding round close notification page and relevant validations before directing the page to the user.

- app/templates/404.html
- app/templates/accessibility_statement.html
- app/templates/contact_us.html
- app/templates/research_opt_in.html
- tests/test_content_routes.py
- tests/test_error_routes.py
The old support email was using the levellingup domain ( fsd.support@levellingup.gov.uk ). This has been updated to the fundingservice.support@communities.gov.uk
> Update support email to communities from levellingup

- app/default/application_routes.py
- app/default/content_routes.py
- app/models/fund.py
- app/templates/dashboard_all.html
- app/templates/dashboard_single_fund.html
- app/templates/tasklist.html
- tests/api_data/test_data.py
- tests/test_dashboard.py
- tests/test_lru_cache.py
- tests/test_routes.py
Now that funds have the `funding_type` property add a visual indiciation any time that we show the "noun" fund "name" property on the dashboard pages.
Note this isn't the same as the "titles" properties which usually are verbs and translated.
Future fund models may model the EOI as a proprety on the fund but for now the questions and configuration for expression of interests are effectively modelled as funds themselves.
> FS-4674 Visually indicate funds with the "EOI" funding type

- pyproject.toml
- uv.lock
The previous lock file had `enum34` added when [werkzeug-dluhc](https://github.com/communitiesuk/funding-service-design-frontend/pull/653) was removed, which is actually only needed for python <3.4.
I'm not sure why this got pulled it - it shouldn't be there. And it broke our deploys, because it overwrites the stdlib `enum` package, which then breaks other stdlib packages.
```
Traceback (most recent call last):
File "/layers/paketo-buildpacks_pip-install/packages/bin/gunicorn",
line 3, in <module>
import re
File "/layers/paketo-buildpacks_cpython/cpython/lib/python3.10/re.py",
line 145, in <module>
class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```
To fix this I just did:
uv remove pyscss
uv add 'pyscss>=1.4.0'
> Re-compile uv lock with pyscss

- app/default/application_routes.py
- tests/conftest.py
[Form Runner - privacy and contact us pages returning 404](https://mhclgdigital.atlassian.net/browse/FS-4783)
We pass the fund and round in the metadata sent in the rehydration token to the Form Runner when a task is opened from the tasklist.
This change only has a visible frontend effect in conjunction with the related change in the Form Runner.
> FS-4783 - Form Runner - privacy and contact us pages returning 404

- copilot/fsd-frontend/manifest.yml
https://mhclgdigital.atlassian.net/browse/FLS-795
- Added sidecar to enable basic auth
- Visit the apply test envs, you should be prompted to provide useranme and password
> FLS-795: Added nginx sidecar for basic auth

- copilot/fsd-frontend/manifest.yml
This is because the `recreate` deployment method leads to downtime, which can cause tests to flake. It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling
> Turn off recreate deploys in test environment

- app/default/eligibility_routes.py
- tests/test_eligibility_routes.py
https://mhclgdigital.atlassian.net/browse/FLS-813
- Updated eligibility result route to get request arguments from the query string passed on from the form runner
- Make sure HSRA VR/RP are live
- Go through the login process
- Click on check eligibility button
- Make sure selecting vacancy register or refurbishment project as answer to question "Why are you applying to this funding?" forwards you to the correct Application tasklist for that round
> FLS-813: Eligibility result route updated

- pyproject.toml
- uv.lock
We don't use these dependencies for pre-processing or bundling css/ js, lets remove them until they're needed.
This repository seems to manually copy over CSS files during the build step - this commit doesn't have an opinion on if thats good or bad but lets only add flask assets back in when its hooked in properly.
> FSPT-119 Remove unused bundling dependencies
