communitiesuk/funding-service-design-frontend

- .github/workflows/govcloud.yml
This will always pass as it just runs the tests and produces a report. Need to add a feature for failing when a certain amount of requests fail.
> FS-394 add performance testing

- .github/workflows/govcloud.yml
Version bump for the ubuntu image used by actions
> updating ubuntu version to latest

- app/templates/index.html
- tests/route_testing_conf.py
- tests/test_accessibility.py
PR that demos a change to hello world to demo the pipeline and PR process
> Demo for hello world

- Dockerfile
Please merge me to gain access to latest version of forms runner
> adding new forms version

- .github/workflows/xforms_builder.yml
- Dockerfile
- app.dockerfile
- app/default/data.py
- app/default/routes.py
- config/envs/default.py
- config/envs/development.py
- config/envs/unit_test.py
Adds dockerfile for app 
*(note alternative filename is because `Dockerfile` in this repo was already used for the form-builder and I didn't want to break anything expecting that to exist.)*
Also fixes config to make  local data configurable to make it more usable in docker context.
> FS-657: add app dockerfile

- manifest.yml
add custom route and point to custom domain for authenticator
> FS-1050: add custom domain for frontend

- .github/workflows/govcloud.yml
- .github/workflows/xforms_builder.yml
- .gitignore
- app.dockerfile
- app/templates/dashboard.html
- manifest.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
> FS-1050 Added custom domain and updated .gitignore

- app/templates/tasklist.html
https://digital.dclg.gov.uk/jira/browse/FS-1191
> added no commplete tasks text

- manifest.yml
#66 inadvertently removed the form-runner deploy, this restores it.
> BAU: restore manifest for form runner

- app/templates/tasklist.html
https://digital.dclg.gov.uk/jira/browse/FS-1190
> Fs 1190 status fix

- .github/workflows/govcloud.yml
- app/templates/tasklist.html
- manifest-test.yml
- manifest.yml
Changes to the frontend app and forms deploy to support custom domains:
- Added the custom routes to the frontend app for dev and test
- Updated workflow to deploy a separate form runner instance to each of dev and test so support the custom cookie domain
> FS-1163 and FS-1050

- .github/workflows/govcloud.yml
Having this as a secret obfuscated the issues previously
> FS-1263: Make form host public and point to domain

- .github/workflows/govcloud.yml
- manifest.yml
Sister PR to https://github.com/communitiesuk/digital-form-builder/pull/12 adds public key secret to form runner.
> FS-1162: add public key to form runner

- form_jsons/config/development.json
- form_jsons/config/production.json
> FS-1162 Forms config updates for jwt authentication

- manifest-dev.yml
Use new custom domain whilst previous one is blocked.
> BAU: Use temporary custom domain

- app/default/routes.py
- app/templates/cookie_policy.html
- app/templates/footer.html
Adding cookie policy page listing following cookie audit.  Resolves FS-1201.
> FS-1201 Adding cookie policy

- manifest-test.yml
Updates custom domains on test, as per #90 for dev.
> BAU: update custom domains on test

- manifest.yml
add service start pages to manifest required by form-builder
> FS-1256: add service start pages to manifest

- app/default/data.py
- app/default/routes.py
- tests/conftest.py
- tests/test_application_summary.py
- tests/test_routes.py
Improve error handling for application store requests.
> Fix get application error handler

- app/templates/tasklist.html
- requirements-dev.txt
- requirements.in
- requirements.txt
Added breadcrumb link.
Only tested locally as application-store down in dev
> Fs 1348 breadcrumb

- config/envs/production.py
required to decode in prod environment
> FS-987: decode JWT in prod environment

- config/envs/default.py
https://digital.dclg.gov.uk/jira/browse/FS-1368
> fs-1368-removed URL suffix

- requirements-dev.in
- requirements-dev.txt
Update dparse version to fix safety warning which was breaking build
> BAU: Update dparse version

- form_jsons/public/applicant-information.json
- form_jsons/public/asset-information.json
- form_jsons/public/community-benefits.json
- form_jsons/public/community-engagement.json
- form_jsons/public/community-representation.json
- form_jsons/public/community-use.json
- form_jsons/public/declarations.json
- form_jsons/public/environmental-sustainability.json
- form_jsons/public/feasibility.json
- form_jsons/public/funding-required.json
- form_jsons/public/inclusiveness-and-intergration.json
- form_jsons/public/local-support.json
- form_jsons/public/organisation-information.json
- form_jsons/public/project-costs.json
- form_jsons/public/project-information.json
- form_jsons/public/project-qualification.json
- form_jsons/public/risk.json
- form_jsons/public/skills-and-resources.json
- form_jsons/public/value-to-the-community.json
Changing the path for the summary pages to fix redirect issues.
> FS-1374 Fix for summary bug

- app/templates/index.html
Updated start page content to match design, dummy/blank links where page has not been created yet
> Update start page content

- app/templates/application_submitted.html
Added correct links to the application summary page
> Fs 1381 summary page links

- form_jsons/public/applicant-information.json
- form_jsons/public/asset-information.json
- form_jsons/public/community-benefits.json
- form_jsons/public/community-engagement.json
- form_jsons/public/community-representation.json
- form_jsons/public/community-use.json
- form_jsons/public/declarations.json
- form_jsons/public/environmental-sustainability.json
- form_jsons/public/feasibility.json
- form_jsons/public/funding-required.json
- form_jsons/public/inclusiveness-and-intergration.json
- form_jsons/public/local-support.json
- form_jsons/public/organisation-information.json
- form_jsons/public/project-costs.json
- form_jsons/public/project-information.json
- form_jsons/public/project-qualification.json
- form_jsons/public/risk.json
- form_jsons/public/skills-and-resources.json
- form_jsons/public/upload-business-plan.json
- form_jsons/public/value-to-the-community.json
Add the back link text configurable to the forms.
> Adding back link to forms

- app/default/routes.py
- app/templates/head.html
- app/templates/header.html
- build.py
- manifest-form-runner.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
- static/src/styles/app.css
- "Sign out" link added to header
- js menu drop down added which appears on small screens when js is enabled
> FS-1450 Add sign-out link

- form_jsons/public/upload-business-plan.json
Optional text removed from the landing page
> optional text removed from landing page

- manifest-form-runner.yml
> FS-1433 Default to Basic Auth On on dev/test forms runner

- Dockerfile
- manifest-form-runner.yml
https://digital.dclg.gov.uk/jira/browse/FS-1482
Dockerfile needs updating to latest after release of runner
> Added env vars to runner manifest for footer changes

- app/default/routes.py
- app/templates/dashboard.html
- app/templates/index.html
- config/envs/default.py
Few UI tweaks:
1. Converting "COMPLETED" to "READY TO SUBMIT" 
2. Ordering dashboard page by status
> UI tweaks to support design for COF launch

- form_jsons/public/applicant-information.json
- form_jsons/public/asset-information.json
- form_jsons/public/community-benefits.json
- form_jsons/public/community-engagement.json
- form_jsons/public/community-representation.json
- form_jsons/public/community-use.json
- form_jsons/public/declarations.json
- form_jsons/public/environmental-sustainability.json
- form_jsons/public/feasibility.json
- form_jsons/public/funding-required.json
- form_jsons/public/inclusiveness-and-intergration.json
- form_jsons/public/local-support.json
- form_jsons/public/organisation-information.json
- form_jsons/public/project-costs.json
- form_jsons/public/project-information.json
- form_jsons/public/project-qualification.json
- form_jsons/public/risk.json
- form_jsons/public/skills-and-resources.json
- form_jsons/public/upload-business-plan.json
- form_jsons/public/value-to-the-community.json
Application questions update as per the new prototype
> FS 1409 update application question forms

- form_jsons/public/organisation-information.json
Updated the different options for `organisation-type` to have unique values, previously they had the same values. Also updated the `conditions` section to account for these unique values.
During investigating realised there were some duplicate, unused conditions around this field so I have removed these.
> Fs 1516 fix org type

- config/envs/default.py
- config/envs/development.py
- config/envs/unit_test.py
Based on the IT Healthcheck we need to set secure properties on the session cookie.
> FS-1501: secure cookies

- form_jsons/public/organisation-information.json
> Updating link fields to use type WebsiteField

- app/filters.py
- app/models/application_parts/sections.py
- form_jsons/public/inclusiveness-and-integration.json
- tests/api_data/endpoint_data.json
- spelling correction of form Inclusiveness and integration 
- Capitilized section & form names as per the prototype
> Bug fix application contents

- .github/workflows/govcloud.yml
- app/create_app.py
- manifest-dev.yml
- manifest-test.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
Adds sentry integration using utils function
> FS-1401: add sentry integration

- .github/dependabot.yml
- .github/workflows/govcloud.yml
- requirements-dev.in
- requirements-dev.txt
Add configurable dependabot.yml file (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval).
I have enabled Dependabot security updates which will cause Dependabot to create pull requests for newly detected vulnerabilities outside of our regular update interval.
> add dependabot.yml

- form_jsons/public/funding-required.json
Adding titles and column names to match prototype
> Adding titles and column names to match prototype

- form_jsons/public/funding-required.json
- form_jsons/public/project-costs.json
Missed a couple of add another titles, made changes to match prototype. removed unused separate page title
> Change to add another titles

- app/default/routes.py
Adding error handling so an exception is raised on frontend is there is a failed submission response from application-store
> BAU: Add error handling to submit route

- manifest-dev.yml
- manifest-test.yml
Spotted this was missing in the course of another task
> BAU: bind apps to logit drain

- app/templates/tasklist.html
- config/envs/default.py
- requirements-dev.txt
- requirements.in
- requirements.txt
adding new CSRF token time limit from new fsd-utils
> fs-1625-replace-expired-csrf-token-page

- form_jsons/public/funding-required.json
- minor content changes updated to the funding-required form following the demo with COF
> FS-1821-contents-update-funding-required-form 

- form_jsons/public/community-benefits.json
- form_jsons/public/inclusiveness-and-integration.json
- form_jsons/public/organisation-information.json
Contents have been update as per the prototype for the following forms:
- Organisation information
- Inclusiveness and integration
- Community benefits
> Update remaining form contents as per the prototype

- form_jsons/public/asset-information.json
- form_jsons/public/project-information.json
Reverts communitiesuk/funding-service-design-frontend#193
> Revert "Updated contents on project information"

- form_jsons/public/community-benefits.json
- form_jsons/public/inclusiveness-and-integration.json
- form_jsons/public/organisation-information.json
Reverts communitiesuk/funding-service-design-frontend#194
> Revert "Update remaining form contents as per the prototype"

- form_jsons/public/skills-and-resources.json
Reverts communitiesuk/funding-service-design-frontend#192
> Revert "added optional multi text field"

- app/templates/cof_r2w2_all_questions.html
https://digital.dclg.gov.uk/jira/browse/FS-1845
Total funding request in the funding required form has not been included in the list of application questions. Also for file upload static questions we need to remove rtf as that is no longer supported.
> Fs 1845 update static content

- form_jsons/public/skills-and-resources.json
Reverts communitiesuk/funding-service-design-frontend#197
> Revert "Revert "added optional multi text field""

- form_jsons/public/skills-and-resources.json
- Recent changes are reverted on skills and resources
> reverted changes on skills and resources

- form_jsons/public/cy/buddion-cymunedol.json
- form_jsons/public/cy/cefnogaeth-leol.json
- form_jsons/public/cy/costau'r-prosiect.json
- form_jsons/public/cy/cyllid-sydd-ei-angen.json
- form_jsons/public/cy/cymhwystra'r-prosiect.json
- form_jsons/public/cy/cynaliadwyedd-amgylcheddol.json
- form_jsons/public/cy/cynhwysiant-ac-integreiddio.json
- form_jsons/public/cy/cynrychiolaeth-gymunedol.json
- form_jsons/public/cy/datganiadau.json
- form_jsons/public/cy/defnydd-cymunedol.json
- form_jsons/public/cy/dichonoldeb.json
- form_jsons/public/cy/gwerth-i'r-gymuned.json
- form_jsons/public/cy/gwybodaeth-am-y-prosiect.json
- form_jsons/public/cy/gwybodaeth-am-y-sefydliad.json
- form_jsons/public/cy/gwybodaeth-am-yr-ased.json
- form_jsons/public/cy/gwybodaeth-am-yr-ymgeisydd.json
- form_jsons/public/cy/lanlwythwch-y-cynllun-busnes.json
- form_jsons/public/cy/risg.json
- form_jsons/public/cy/sgiliau-ac-adnoddau.json
- form_jsons/public/cy/ymgysylltu-â'r-gymuned.json
Adding is welsh flag for form runner welsh changes.
Changing summary title
> Welsh Summary changes

- form_jsons/public/cy/cyllid-sydd-ei-angen.json
- Page title bug fix
- Output added for save & return
- Conditions bug resolved
> bug-fix-funding-required-form

- requirements-dev.txt
- requirements.in
- requirements.txt
Bumps funding-service-design-utils to 1.0.13 to include locale sniffing functionality.
https://github.com/communitiesuk/funding-service-design-utils/pull/48/
> FS-1773: Bump fsd-utils version for locale sniffing

- .github/workflows/build-deploy-forms.yml
- .github/workflows/govcloud.yml
Will run shared tests after a deploy
> adding params to run shared tests

- .github/workflows/tag-to-release.yaml
GitHub didn't like the previous regex, so trying with separate regexes...
> FS-2172: separate regex 

- .github/workflows/tag-to-release.yaml
Use main branch now https://github.com/communitiesuk/funding-design-service-workflows/pull/28 is merged.
> FS-2172: use main branch for shared workflow

- form_jsons/public/cy/costau'r-prosiect.json
- form_jsons/public/cy/cyllid-sydd-ei-angen.json
- form_jsons/public/en/funding-required.json
- form_jsons/public/en/project-costs.json
A more descriptive amount field was need for blind user using a screen reader
> Fs 2196 More descriptive amount fields

- app/default/application_routes.py
- app/default/routes.py
- config/envs/default.py
- pytest.ini
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/api_data/endpoint_data.json
- tests/test_default_fund_round.py
- tests/test_initialisation.py
Updated to pull default round ID from utils, to account for cof r2w3
> Fs 2180 cof r2w3

- .github/workflows/govcloud.yml
- tests/test_accessibility.py
Updates the workflow to run unit tests before deploy, then just the accessibility tests after deploy
> Bau deploy order

- app/helpers.py
Added a new variable called form_session_identifier which will be used for making session ids in the runner unique per application.
> Added form session identifier

- app/templates/footer.html
- tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2202
> More descriptive footer title

- app/templates/application_submitted.html
- app/templates/header.html
- form_jsons/config/production.json
Update feedback URL for Window 3
> FS-2340: update feedback URL

- app/templates/partials/tasklist_submit.html
- static/src/styles/tasklist.css
https://digital.dclg.gov.uk/jira/browse/FS-2300
Changing the width on the submit application box to match prototype
- Complete all sections of an application (or in code remove the check for completed status int he tasklist.html)
- See the box
> Submit application box width change

- .github/workflows/build-deploy-forms.yml
- app/templates/header.html
- static/src/styles/tasklist.css
https://digital.dclg.gov.uk/jira/browse/FS-2331
Change to css to make the sign out on the front end match the one in the forms
> Css change for signout

- app/default/application_routes.py
- requirements-dev.txt
- requirements.in
- requirements.txt
Ticket: https://digital.dclg.gov.uk/jira/secure/RapidBoard.jspa?rapidView=110&projectKey=FS&view=detail&selectedIssue=FS-2052&quickFilter=542
This PR addresses a bug that affected the translation of a static page. To resolve the issue, I updated the frontend with a new version of the utils service that includes the necessary functionality. This will ensure that the translation is correctly applied to the page.
> FS-2052-switch-language-for-static-question-page

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- Dockerfile
- requirements-dev.in
- requirements-dev.txt
- requirements.txt
BAU
- Adding debugpy to requirements-dev.in so that we can use this for debugging in the docker runner
- Ensuring the Dockerfile installs requirements-dev.txt so debugpy is included
- Also updated pip-tools as the latest version has an API change that is causing errors running pip-compile if you don't upgrade
- Checkout the branch https://github.com/communitiesuk/funding-service-design-docker-runner/tree/bau-debug-containers of the docker runner
- Run `docker compose build frontend` to rebuild this app
- Run `docker compose up frontend` and connect a debugger as per the README in docker-runner
n/a
> bau - adding debugpy to dependencies and dockerfile

- .vscode/launch.json
- app/create_app.py
- app/default/account_routes.py
- app/default/application_routes.py
- app/default/content_routes.py
- app/default/data.py
- app/default/error_routes.py
- app/default/routes.py
- app/filters.py
- app/models/application.py
- app/models/application_display_mapping.py
- app/models/round.py
- app/templates/404.html
- app/templates/500.html
- app/templates/contact_us.html
- app/templates/footer.html
- app/templates/partials/contact_details.html
- app/templates/partials/tasklist_section.html
- config/envs/default.py
- config/envs/unit_test.py
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/api_data/endpoint_data.json
- tests/test_data.py
- tests/test_filters.py
- tests/test_start_page.py
- tests/test_tasklist.py
- tests/test_user_validation.py
https://digital.dclg.gov.uk/jira/browse/FS-2628
Change description
The fund store is now using a Postgres DB, that has changed the way in which data is returned from the fund_store api that this microservice consumes. The changes in this PR adapt to consume the new fund_store responses.
Unit tests and other appropriate tests added or updated
README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo").
How to test
pytest
Screenshots of UI changes (if applicable)
NA
> Fund_db api Postgres updates

- app/create_app.py
- app/default/content_routes.py
- app/default/data.py
https://digital.dclg.gov.uk/jira/browse/FS-2787
Fixed broken contact us url from following pages
1. Magic link landing page
2. Tasklist page
3. Form pages
4. 404 error pages
5. "You are not logged in" page
> fix broken contact us page

- app/default/data.py
- tests/api_data/endpoint_data.json
https://digital.dclg.gov.uk/jira/browse/FS-2808
- Added check if fund or round doesn't exist
- Display warnings when tried to access non-existent funds or rounds
> added check if fund or round doesnt exist

- app/default/account_routes.py
- app/templates/dashboard_single_fund.html
- app/templates/partials/applications_table.html
Fund and round short name passed to task list page allowing these pages to configure test according to the arguments in the url
> Fund_short_name, round_short_name passed to args correctly

- app/create_app.py
- app/default/application_routes.py
- tests/test_tasklist.py
- tests/test_user_validation.py
https://digital.dclg.gov.uk/jira/browse/FS-2819
Added cache control, disable going back to tasklist from submit page instead redirect to dashboard
>  FS-2819: Redirect to dashboard when clicked back from submit

- app/default/error_routes.py
- Add stacktrace to error logs so we can track down where each error happened
> BAU: Log stack trace on errors

- config/envs/production.py
Switch multifund dashboard on in frontend
> BAU-switch-multifund-on

- app/create_app.py
- tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2851
https://digital.dclg.gov.uk/jira/browse/FS-2874
Fixing service name issue
> Updating service name

- app/templates/cof_r3_all_questions.html
> updated percentages for sections

- app/create_app.py
- app/templates/dashboard_all.html
https://digital.dclg.gov.uk/jira/browse/FS-2879
Make contact_us page & service names in banner dynamic in the tasklist page
> FS-2879: Make urls dynamic in create_app

- app/default/application_routes.py
- app/templates/tasklist.html
make service name on tasklist page dynamic
> fs-2854-ns-service-name

- app/default/application_routes.py
- app/templates/tasklist.html
hide all questions link for funds that don't need this + quick fix for fund title on tasklist page
> fs-2847-all-questions-link

- app/templates/accessibility_statement.html
Adding night shelter to accessiblity statmenet - translations to follow in subsequent ticket
Navigate to accessiblitiy statement and see night shelter in the lsit of services
> adding night shelter to accessiblity statement

- app/templates/accessibility_statement.html
- app/templates/partials/contact_details.html
Updating contact us page to add details of requesting a callback
Run locally and navigate to contact us page
> Fs 2855 contact us callback

- app/default/account_routes.py
- app/templates/dashboard_all.html
- app/templates/dashboard_single_fund.html
- app/templates/partials/applications_table.html
removing unnecassery query params
> fs-2837-remove-params

- app/default/content_routes.py
- app/models/fund.py
Adding NSTF to the allowed list of funds - fixes several bugs around not displaying the right URLs eg feedback, contact us, privacy
Navigate to start page - urls in footer should be relevant to selected fund
n/a
> fs-2964 adding nstf to allowed short codes

- app/templates/application_submitted.html
https://digital.dclg.gov.uk/jira/browse/FS-2968
https://digital.dclg.gov.uk/jira/browse/FS-2967
The survey link directs the applicant to the respective fund survey. 
> fixed feedback link in submit page

- app/create_app.py
- app/default/content_routes.py
- app/default/data.py
- app/helpers.py
- app/templates/contact_us.html
- tests/conftest.py
- tests/test_content_routes.py
- tests/test_data.py
- tests/test_routes.py
Continuing from previous BAU PR to add unit tests for find fund and round, now reusing those methods for the content URLs, and added tests.
> Bau tidy find fund round

- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/test_dashboard.py
- tests/test_tasklist.py
- tests/test_user_validation.py
> bau-update-utils-2.0.5

- .github/workflows/deploy.yml
- .github/workflows/package.yml
- .github/workflows/tag-to-release.yml
- Procfile
- docs/run.md
https://dluhcdigital.atlassian.net/browse/FS-3206
Add paketo build and include it in the workflow
Checked container boots and begins producing output
> FS-3206 - Add paketo build and include in workflow

- .github/workflows/copilot.yml
- manifest-dev.yml
- manifest-test.yml
https://dluhcdigital.atlassian.net/browse/FS-3278
Dummy copilot workflow
> FS-3278 Add dummy copilot workflow

- .github/workflows/deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3083
Split out pre-deploy unit testing
> FS-3083 add pre deploy

- app/templates/application_submitted.html
https://dluhcdigital.atlassian.net/browse/FS-3367
- Removes another feedback link from the front-end
> FS-3367: Remove feedback

- app/templates/cof_r3_all_questions.html
> cof-r3w2-config-full-q-list

- .github/workflows/deploy.yml
- .github/workflows/tag-to-release.yml
https://dluhcdigital.atlassian.net/browse/FS-3414
Change outdated reference to fds to fsd.
> FS-3414 Amend fds to fsd

- app/templates/cof_r3_all_questions.html
https://dluhcdigital.atlassian.net/browse/FS-3458
Updating all questions to match prototype
Go to all questions to test the changes
> Updating questions to match prototype

- app/templates/cof_r3_all_questions.html
https://dluhcdigital.atlassian.net/browse/FS-3458
More Questions fixes to match the prototype
Navigate to the all questions page for r3w"
> More questions fix

- Procfile
- config/envs/default.py
- config/envs/dev.py
- config/envs/production.py
- config/envs/test.py
- copilot/.workspace
- copilot/environments/addons/assessment-import-queue.yml
- copilot/environments/addons/form-uploads.yml
- copilot/environments/addons/funding-service-magic-links.yml
- copilot/environments/dev/manifest.yml
- copilot/environments/test/manifest.yml
- copilot/fsd-frontend/manifest.yml
Adding Copilot Configuration and Environment setups to frontend
> FS-3317 Copilot Config

- app/templates/cyp_r1_all_questions.html
Removing S from Hong Kong British Nationals
> Removing s from hong kong british national

- app/default/application_routes.py
- app/helpers.py
- app/templates/partials/tasklist_section.html
feature toggle for section feedback to display or not
If `has_section_feedback` = True, section feedback is displayed on frontend
> FS-3582 add feature toggle for section feedback

- app/default/error_routes.py
- Change this log to a warning, so we don't get spammed in slack anytime someone 401s
> BAU: Don't log errors on 401, just warn

- app/templates/dpif_r2_all_questions.html
FS-3608 Added html page for all questions for DPIF
> Adding generated all questions page for DPIF

- app/templates/dpif_r2_all_questions.html
Re-ran the script to generate the all questions page following spelling corrections on the forms.
> FS-3608 rerun script after updates to forms

- static/src/styles/tasklist.css
https://dluhcdigital.atlassian.net/browse/FS-3514
> FS-3514-align-assessment-complete-alert-box

- app/create_app.py
- app/templates/head.html
- Replace with service_title as that's what's used there anyways atm
> BAU: Replace hardcoded COF metadata

- app/filters.py
- tests/test_filters.py
- Fix time to meet govuk style guidelines
---
> BAU: Fix time to meet govuk style guidelines

- .github/workflows/copilot_deploy.yml
- .github/workflows/deploy.yml
- copilot/fsd-frontend/manifest.yml
* Adding copilot deploy workflow
* Updating paas deploy
* Adding sentry to manifest
+ref: FS-3627
+semver: minor
> Adding automated copilot deploys to frontend

- .github/workflows/copilot_deploy.yml
Small update to the workflows to _actually_ automatically deploy
> FS-3627 Updated copilot to create the assets

- app/templates/base.html
- app/templates/head.html
https://dluhcdigital.atlassian.net/browse/FS-3567
Added GA tag manager to base and head, added consent mode defaults to…granted for testing, will be switching to denied before any prod release
> Added GA tag manager to base and head

- app/templates/cookie_policy.html
Confirm Google Analytics cookie table exists on the cookie policy page and that it matches govuk formatting
> FS-3633 Update cookies page to include google analytics

- app/templates/base.html
moved GT code from unused content block to body end block
> moved GT code from unused content block to body end block

- config/envs/default.py
added the sha's of the 2 script tags added to the header tag as GA requires scripts to be run but the CSP was blocking any script being run. Added the sha of the script tag 
> added the sha's of the 2 script tags added to the header tag as GA re

- app/templates/base.html
- app/templates/head.html
- config/envs/default.py
> removed GA changes to allow prod release

- app/templates/base.html
- app/templates/head.html
- config/envs/default.py
revert changes from this PR
https://github.com/communitiesuk/funding-service-design-frontend/pull/428/files#diff-830b41638f32c4afb3ccef5bf4c2c26af86371a2e52b088f895297c5577bca63
> Revert "removed GA changes to allow prod release"

- app/templates/head.html
> removed consent mode from head

- app/create_app.py
- app/templates/base.html
- app/templates/head.html
- config/envs/default.py
moved the GA code behind an env var called GOOGLE_ANALYTICS to protect prod and only be enabled on UAT
> moved the GA code behind env var

- config/envs/default.py
- Add google analytics url so we can hit the collect endpoint
> BAU: Add google-analytics url

- config/envs/default.py
> added sha for google script

- app/templates/head.html
- config/envs/default.py
Added cookie consent defaulting to denied 
> Added default GA cookie consent to denied

- app/create_app.py
- app/templates/base.html
- app/templates/head.html
- config/envs/default.py
> Removed GA env var toggle and added consent default to GA

- .github/workflows/copilot_deploy.yml
- .github/workflows/environment.yml
https://dluhcdigital.atlassian.net/browse/FS-3718
Add deploy to dev workflow and the other environments as a parameterised block.
> FS-3718 - Add dev deploy

- .github/workflows/copilot_deploy.yml
> BAU - pass environment

- copilot/fsd-frontend/manifest.yml
Fix the alias for dev/uat - amend the redislinks url.
> BAU - fix alias

- copilot/fsd-frontend/manifest.yml
* To allow for a smoother bootup, increase CPU to deal with the initial spikes in CPU usage.
+ref: BAU
+semver: minor
> BAU - Increasing CPU requirements

- .github/workflows/copilot_deploy.yml
- copilot/fsd-frontend/manifest.yml
Upping CPU and RAM requirements, upping count of tasks
> BAU Upping CPU and RAM requirements, upping count of tasks

- .github/workflows/copilot_deploy.yml
- .github/workflows/deploy.yml
* Removing expired E2E_PAT configuration, added the new shared token to deploy workflow
* Updating copilot deployment to have sandbox seperated from releases by deployment testing
+ref: FS-3797
+semver: minor
> FS-3797 - Update Workflows

- app/templates/all_questions/en/cof_r3w3_all_questions_en.html
https://dluhcdigital.atlassian.net/browse/FS-3820
Adding all questions for English
On an English form, click the all questions form
> FS-3820 - Adding en question for r3w3

- .github/workflows/copilot_deploy.yml
- copilot/fsd-frontend/manifest.yml
Amend workflow to follow expected route from dev->test->uat->prod
> FS-3797 workflows

- .github/workflows/copilot_deploy.yml
- copilot/fsd-frontend/manifest.yml
Amend production to prod for pre-award URLs
> FS-3797 - Amend production to prod for deployment

- app/templates/all_questions/cy/cof_r3w3_all_questions_cy.html
https://dluhcdigital.atlassian.net/browse/FS-3820
Adding all questions page for welsh forms
Test the all questions page
> FS-3820 Adding welsh all questions page

- app/templates/application_submitted.html
> Added banner to application_submitted page

- app/default/application_routes.py
> Added variable for section feedback

- Dockerfile
- requirements-dev.in
- requirements-dev.txt
- requirements.txt
https://dluhcdigital.atlassian.net/browse/FS-4005
Use forked `werkzeug` package in the requirements
linked PR https://github.com/communitiesuk/funding-service-design-docker-runner/pull/55
> FS-4005 use custom werkzeug in requirements

- .pre-commit-config.yaml
- requirements-dev.in
- requirements-dev.txt
> removing bandit from requirements dev

- app/templates/fund_start_page.html
- app/templates/tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-4072
https://dluhcdigital.atlassian.net/browse/FS-4074
https://dluhcdigital.atlassian.net/browse/FS-4075
Minor EOI form bug fixes
> FS-4072 eoi fixes

- app/default/application_routes.py
- app/default/data.py
- app/helpers.py
- config/envs/default.py
https://dluhcdigital.atlassian.net/browse/FS-4036
- Move EOI decision calculation to `application-store`
> FS-4036 move eoi decision calculation to app store

- app/templates/dashboard_all.html
- app/templates/dashboard_single_fund.html
- app/templates/partials/applications_table.html
Adding if block around column name on dashboard to make sure column names match for EOI
> fs-4172 updating display of project name for cof eoi

- app/templates/application_submitted.html
- app/templates/partials/contact_details.html
- app/templates/tasklist.html
- app/translations/cy/LC_MESSAGES/messages.po
- messages.pot
Updated templates with missing translation tags
> Added missing translation tags

- app/default/application_routes.py
- app/templates/eoi_submitted.html
- app/translations/cy/LC_MESSAGES/messages.po
- messages.pot
Updating EOI submission content
> Fs 4167 eoi submit

- app/templates/all_questions/en/cof-eoi_r1_all_questions_en.html
- app/templates/tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-4097
https://dluhcdigital.atlassian.net/browse/FS-4106
Adding the all questions page for COF EOI
Adding the FSD contact email for all funds
> FS-4097 Adding all questions page and updaing fsd email

- app/templates/tasklist.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4132
The fund title text has been capitalized "Community Ownership Fund"
> FS-4132-capitalize-community-ownership-fund-text

- app/templates/all_questions/cy/cof_r4w1_all_questions_cy.html
- app/templates/all_questions/en/cof_r4w1_all_questions_en.html
https://dluhcdigital.atlassian.net/browse/FS-4138
Adding all questions page for cof round 4 window 1
Click the link "full list of application questions"
> FS-4138 - Adding all questions for COFR4W1

- app/templates/partials/tasklist_section.html
- Wrap in list item to fix accessibility issue
> FS-4180: Wrap in list item to fix accessibility issue

- app/templates/all_questions/cy/cof_r4w1_all_questions_cy.html
https://dluhcdigital.atlassian.net/browse/FS-4142
Adding welsh translation to all questions page
> FS-4142 All question added missing welsh translations

- app/templates/all_questions/cy/cof-eoi_r1_all_questions_cy.html
https://dluhcdigital.atlassian.net/browse/FS-4238
Adding the all questions page in welsh so it will not longer throw and exception 
Click the all questions button on a welsh application
> FS-4238 - Adding COF EOI all questions in welsh

- app/templates/all_questions/cy/cof-eoi_r1_all_questions_cy.html
- app/templates/all_questions/en/cof-eoi_r1_all_questions_en.html
https://dluhcdigital.atlassian.net/browse/FS-4222
Updating cof eoi forms to have correct ordering and include new question
> FS-4222 Updating all question to include new question and correct order of questions

- app/templates/all_questions/cy/cof-eoi_r1_all_questions_cy.html
- app/templates/all_questions/en/cof-eoi_r1_all_questions_en.html
https://dluhcdigital.atlassian.net/browse/FS-4222
Change to the all questions page to fix cosmetic issues
See all questions page
> FS-4222 All questions cosmetic changes

- app/templates/tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-4270
Fix for final feedback page causing crash
> FS-4270 - Fixing issue causing crash on last feedback page

- app/templates/all_questions/cy/cof_r4w1_all_questions_cy.html
- app/templates/all_questions/en/cof_r4w1_all_questions_en.html
https://dluhcdigital.atlassian.net/browse/FS-4246
Re ran the cof all questions script
> FS-4264 - Updating Cof all questions pages

- .github/workflows/copilot_deploy.yml
Updated copilot_deploy workflow to use shared workflow for determining jobs to run
> Fs 4294 shared determine jobs

- .github/workflows/copilot_deploy.yml
Changing job name to remove 'test' for feature branches
> fs-4291 temp branch to test changes in workflows repo

- app/templates/all_questions/en/hsra_r1_all_questions_en.html
FS-4348: Add HSRA application guidance  All questions templates
1. Add HSRA application guidance All question templates
> FS-4348: Add HSRA application guidance section for all questions template

- app/templates/all_questions/cy/cof_r4w2_all_questions_cy.html
- app/templates/all_questions/en/cof_r4w2_all_questions_en.html
FS-4386: Fix all questions template for COF-r4w2
> FS-4386: Fix all questions template for COF-r4w2

- app/default/application_routes.py
- app/default/routes.py
- app/templates/fund_start_page.html
- app/templates/tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-4398
- Contact details updated for COF-R4W2 and COF-EOI
- Go through the pages mentioned in the ticket and verify changes
> FS-4398: Contact details updated for COF-R4W2 and COF-EOI

- app/templates/partials/round_closed_warning.html
Updating round closed warning as per FS-4430 to show pre-election message for EOI
> fs-4430 adding pre-election text to round closed warning, just for EOI

- app/templates/all_questions/en/hsra_r1_all_questions_en.html
https://dluhcdigital.atlassian.net/browse/FFE-266
- Auction-costs template removed
- Text changed as per requirements
- Create a new application
- See if expected changes are appearing
> FS-4413: HSRA application text updates

- app/default/application_routes.py
Bug fix for title number in research survey
> Fix bug for title number in research survey

- app/create_app.py
- app/filters.py
- app/templates/dashboard_single_fund.html
While user testing the withdraw/delete feature, we found applicants were confused about whether a round or window was open and expected to see the submission deadline clearly displayed on their dashboard.
Date format needs should be full month along with welsh translation
> FS-4422:deadline-for-applications-welsh-trans-v3

- app/templates/fund_start_page.html
1 Access front end application
2 Change language to Welsh
3 Verify Date format - should display in Welsh format.
Manually tested
> FS-4525:date-format-welsh-lang-change

- app/filters.py
- app/templates/fund_start_page.html
1 Access front end application
2 Change language to Welsh
3 Verify Date format - should display in Welsh format.
Manlually tested
> FS-4525:date-format-welsh-lang-change-v2

- app/templates/fund_start_page.html
- app/templates/tasklist.html
Date Format- Welsh date format still showing in english language
Manually checked
> FS-4525:date-format-welsh-lang-change-v3

- app/templates/partials/tasklist_section.html
No date and time is required in the feedback session except for submission deadline
Manually tested
> FS-4526:date-removal-feedback-section

- copilot/fsd-frontend/manifest.yml
We are not using this so can be safely removed
> BAU: remove additional alias

- config/envs/default.py
- config/envs/development.py
- copilot/fsd-frontend/manifest.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
Use the token associated with this app in the copilot manifest.
Note this also updates the default behavior to use the common config logic updated as part of this change.
- ~[ ] Unit tests and other appropriate tests added or updated~
- ~[ ] README and other documentation has been updated / added (if needed)~
> FS-4647 Use provisioned token and bump shared utils

- app/create_app.py
- app/default/application_routes.py
- app/filters.py
- app/helpers.py
- app/templates/partials/applications_table.html
- app/templates/tasklist.html
- tests/test_tasklist.py
Reverts communitiesuk/funding-service-design-frontend#627
The form builder/ runner is in an inconsistent state across environments which can lead to quite a few edge cases for how the behaviour here is processed by the form runner.
We should introduce this functionality when its stable and we can be confident it the flag will be appropriately received.
> Revert "FS-3664 View submitted applications and applications for previous rounds"

- requirements-dev.txt
- requirements.txt
Bump utils to pick up changes from https://github.com/communitiesuk/funding-service-design-utils/releases/tag/5.1.1
> BAU: bump utils

- app/default/application_routes.py
- app/helpers.py
> fix notification url issue

- app/default/error_routes.py
- app/templates/base.html
- app/templates/cookie_policy.html
- app/templates/head.html
- app/templates/header.html
There are a few more places where `service_title` needs replacing after the recent change.
Tests passing?
> Replace service_title everywhere

- app/create_app.py
- app/default/content_routes.py
- app/templates/footer.html
privacy link fix added when accessed from accessibility_statement url.
- [x ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS: Bugfix privacy link access from accessability link in fund start page

- app/templates/all_questions/en/dpif_r3_all_questions_en.html
1. Be on latest docker-runner and all other repos
2. Git checkout `run-dpif-r3` branch on:
- digital-form-builder-adapter
- funding-service-pre-award-stores
- funding-service-design-frontend
- funding-service-design-notification
3. `make up`
4. Annoying extra step because open date is in the future:
```
docker exec funding-service-pre-award-stores-1 python -m fund_store.scripts.amend_round_dates -q update-round-dates-fab --fund_short_name DPIF --round_short_name R3 -o PAST -d FUTURE
```
5. Go to https://frontend.levellingup.gov.localhost:3008/funding-round/DPIF/R3
> Adding DPIF-R3 template
